In [1]:
import numpy as np

Creating a list

In [2]:
L = np.array([1, 2, 3, 4])
print(L)
print(type(L))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
print(L.shape)

(4,)


In [4]:
L2 = [8, 9, 0, 1.0, 2]
L3 = np.array(L2)
print(L3)

[8. 9. 0. 1. 2.]


In [5]:
V2 = np.array([4, 1, 2, 9, 10])
V2

array([ 4,  1,  2,  9, 10])

In [6]:
V2.shape

(5,)

In [7]:
V3 = V2.reshape((-1, 1))
V3

array([[ 4],
       [ 1],
       [ 2],
       [ 9],
       [10]])

In [8]:
print(V3)
print(V3.shape)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]
(5, 1)


In [9]:
V3[0]

array([4])

In [10]:
print(V3[0])
print(type(V3[0]))

[4]
<class 'numpy.ndarray'>


In [11]:
print(V2[0])
print(type(V2[0]))

4
<class 'numpy.int64'>


Matrices


In [12]:
M = np.array([[1, 2, 4, 5], [0, -1, -2, 10]])
print(M)
print(M.shape)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]
(2, 4)


In [13]:
r1 = M[0]
print(r1)

[1 2 4 5]


In [14]:
e1 = M[0,0]
print(e1)

1


In [15]:
e1 = M[:,2]
print(e1)

[ 4 -2]


In [16]:
e1 = M[1, 2:]
print(e1)

[-2 10]


Tensor


In [17]:
M1 = np.array(([1, 2, 3], [4, 5, 6]))
M2 = np.array(([-1, -2, -3], [-4, -5, -6]))
M3 = np.array(([0, 1, 10], [20, 0, 30]))
T = np.stack((M1, M2, M3))

In [18]:
print(M1.shape)
print(T.shape)

(2, 3)
(3, 2, 3)


In [19]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]

 [[ 0  1 10]
  [20  0 30]]]


In [20]:
print(V3)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]


In [21]:
V3

array([[ 4],
       [ 1],
       [ 2],
       [ 9],
       [10]])

In [22]:
V4 = 3 * V3
print(V3)
print(V4)V4

SyntaxError: invalid syntax (3023824002.py, line 3)

In [ ]:
V4 = 0.3 * V3
V4

In [ ]:
print(V4)

In [ ]:
print(M)

In [ ]:
M4 = 10 * M
print(M4)

In [ ]:
M5 = M * 10
print(M5)

In [ ]:
M6 = np.multiply(0.4, M)
print(M6)

In [ ]:
print(V2)

In [ ]:
V5 = np.transpose(V2)

In [ ]:
print(V5)

In [ ]:
print(V5.shape)
print(V2.shape)

In [ ]:
print(V3)

In [ ]:
V6 = np.transpose(V3)
print(V6)

In [ ]:
V7 = np.transpose(V6)
print(V7)

In [ ]:
print(V7.shape)
print(V6.shape)
print(V2.shape)

In [ ]:
print(M)

In [ ]:
Mt = np.transpose(M)
print(Mt)
print(Mt.shape)

In [ ]:
print(M.shape)

In [ ]:
print(V3)

In [ ]:
print(V4)

In [ ]:
V8 = V3 + V4
print(V8)

In [ ]:
V9 = V3 + (0.5*V4)
print(V9)

In [ ]:
V10 = V3 - V4
print(V10)

In [ ]:
print(V3 - V3)

In [ ]:
print(M)

In [ ]:
print(M2)

In [ ]:
print (M3)

In [ ]:
M7= M2 + M3
print(M7)

In [ ]:
M8 = 2*M2 + M3
print(M8)

In [ ]:
M8 = M2 - M2
print(M8)

In [23]:
M8 = M3 - M2
print(M8)

[[ 1  3 13]
 [24  5 36]]


In [24]:
V = np.array([1, 2, 4, 6])
V2 = np.array([-1, 3, -2, -3])
p1 = np.dot(V, V2)
print(p1)

-21


In [25]:
V3 = V2.reshape(-1, 1)
print(V3)

[[-1]
 [ 3]
 [-2]
 [-3]]


In [26]:
print("shape: V", V.shape)
print("shape: V3", V3.shape)
p2 = np.dot(V, V3)
print(p2)

shape: V (4,)
shape: V3 (4, 1)
[-21]


In [27]:
print(p2[0])

-21


In [28]:
M

array([[ 1,  2,  4,  5],
       [ 0, -1, -2, 10]])

In [29]:
print(M)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]


In [30]:
print(M2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [31]:
print(M3)

[[ 0  1 10]
 [20  0 30]]


In [32]:
print(M4)

NameError: name 'M4' is not defined

In [33]:
M4 = np.transpose(M3)
print(M4)

[[ 0 20]
 [ 1  0]
 [10 30]]


In [34]:
print(M3)

[[ 0  1 10]
 [20  0 30]]


In [35]:
print(M3.shape)
print(M4.shape)

(2, 3)
(3, 2)


In [38]:
M5 = M3 @ M4
print(M5.shape)
print(M5)

(2, 2)
[[ 101  300]
 [ 300 1300]]


In [39]:
row1 = M3[0]
print(row1)

[ 0  1 10]


In [40]:
col1 = M4[:,0]

In [41]:
print(col1)

[ 0  1 10]


In [42]:
print(np.dot(row1, col1))

101


In [43]:
print(M2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [44]:
print(M3)

[[ 0  1 10]
 [20  0 30]]


In [45]:
M7 = M2 * M3
print(M7)

[[   0   -2  -30]
 [ -80    0 -180]]
