In [1]:
import numpy as np

Creating a list

In [2]:
L = np.array([1, 2, 3, 4])
print(L)
print(type(L))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
print(L.shape)

(4,)


In [4]:
L2 = [8, 9, 0, 1.0, 2]
L3 = np.array(L2)
print(L3)

[8. 9. 0. 1. 2.]


In [6]:
V2 = np.array([4, 1, 2, 9, 10])
V2

array([ 4,  1,  2,  9, 10])

In [7]:
V2.shape

(5,)

In [8]:
V3 = V2.reshape((-1, 1))
V3

array([[ 4],
       [ 1],
       [ 2],
       [ 9],
       [10]])

In [9]:
print(V3)
print(V3.shape)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]
(5, 1)


In [11]:
V3[0]

array([4])

In [14]:
print(V3[0])
print(type(V3[0]))

[4]
<class 'numpy.ndarray'>


In [15]:
print(V2[0])
print(type(V2[0]))

4
<class 'numpy.int64'>


Matrices


In [16]:
M = np.array([[1, 2, 4, 5], [0, -1, -2, 10]])
print(M)
print(M.shape)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]
(2, 4)


In [17]:
r1 = M[0]
print(r1)

[1 2 4 5]


In [20]:
e1 = M[0,0]
print(e1)

1


In [21]:
e1 = M[:,2]
print(e1)

[ 4 -2]


In [23]:
e1 = M[1, 2:]
print(e1)

[-2 10]


Tensor


In [26]:
M1 = np.array(([1, 2, 3], [4, 5, 6]))
M2 = np.array(([-1, -2, -3], [-4, -5, -6]))
M3 = np.array(([0, 1, 10], [20, 0, 30]))
T = np.stack((M1, M2, M3))

In [27]:
print(M1.shape)
print(T.shape)

(2, 3)
(3, 2, 3)


In [28]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]

 [[ 0  1 10]
  [20  0 30]]]
