In [2]:
import numpy as np

Creating a list

In [3]:
L = np.array([1, 2, 3, 4])
print(L)
print(type(L))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
print(L.shape)

(4,)


In [5]:
L2 = [8, 9, 0, 1.0, 2]
L3 = np.array(L2)
print(L3)

[8. 9. 0. 1. 2.]


In [6]:
V2 = np.array([4, 1, 2, 9, 10])
V2

array([ 4,  1,  2,  9, 10])

In [7]:
V2.shape

(5,)

In [8]:
V3 = V2.reshape((-1, 1))
V3

array([[ 4],
       [ 1],
       [ 2],
       [ 9],
       [10]])

In [9]:
print(V3)
print(V3.shape)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]
(5, 1)


In [10]:
V3[0]

array([4])

In [11]:
print(V3[0])
print(type(V3[0]))

[4]
<class 'numpy.ndarray'>


In [12]:
print(V2[0])
print(type(V2[0]))

4
<class 'numpy.int64'>


Matrices


In [13]:
M = np.array([[1, 2, 4, 5], [0, -1, -2, 10]])
print(M)
print(M.shape)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]
(2, 4)


In [14]:
r1 = M[0]
print(r1)

[1 2 4 5]


In [15]:
e1 = M[0,0]
print(e1)

1


In [16]:
e1 = M[:,2]
print(e1)

[ 4 -2]


In [17]:
e1 = M[1, 2:]
print(e1)

[-2 10]


Tensor


In [18]:
M1 = np.array(([1, 2, 3], [4, 5, 6]))
M2 = np.array(([-1, -2, -3], [-4, -5, -6]))
M3 = np.array(([0, 1, 10], [20, 0, 30]))
T = np.stack((M1, M2, M3))

In [19]:
print(M1.shape)
print(T.shape)

(2, 3)
(3, 2, 3)


In [20]:
print(T)

[[[ 1  2  3]
  [ 4  5  6]]

 [[-1 -2 -3]
  [-4 -5 -6]]

 [[ 0  1 10]
  [20  0 30]]]


In [21]:
print(V3)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]


In [22]:
V3

array([[ 4],
       [ 1],
       [ 2],
       [ 9],
       [10]])

In [24]:
V4 = 3 * V3
print(V3)
print(V4)V4

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]
[[12]
 [ 3]
 [ 6]
 [27]
 [30]]


In [25]:
V4 = 0.3 * V3
V4

array([[1.2],
       [0.3],
       [0.6],
       [2.7],
       [3. ]])

In [26]:
print(V4)

[[1.2]
 [0.3]
 [0.6]
 [2.7]
 [3. ]]


In [27]:
print(M)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]


In [28]:
M4 = 10 * M
print(M4)

[[ 10  20  40  50]
 [  0 -10 -20 100]]


In [29]:
M5 = M * 10
print(M5)

[[ 10  20  40  50]
 [  0 -10 -20 100]]


In [30]:
M6 = np.multiply(0.4, M)
print(M6)

[[ 0.4  0.8  1.6  2. ]
 [ 0.  -0.4 -0.8  4. ]]


In [31]:
print(V2)

[ 4  1  2  9 10]


In [32]:
V5 = np.transpose(V2)

In [33]:
print(V5)

[ 4  1  2  9 10]


In [34]:
print(V5.shape)
print(V2.shape)

(5,)
(5,)


In [35]:
print(V3)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]


In [36]:
V6 = np.transpose(V3)
print(V6)

[[ 4  1  2  9 10]]


In [37]:
V7 = np.transpose(V6)
print(V7)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]


In [38]:
print(V7.shape)
print(V6.shape)
print(V2.shape)

(5, 1)
(1, 5)
(5,)


In [39]:
print(M)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]


In [40]:
Mt = np.transpose(M)
print(Mt)
print(Mt.shape)

[[ 1  0]
 [ 2 -1]
 [ 4 -2]
 [ 5 10]]
(4, 2)


In [41]:
print(M.shape)

(2, 4)


In [42]:
print(V3)

[[ 4]
 [ 1]
 [ 2]
 [ 9]
 [10]]


In [43]:
print(V4)

[[1.2]
 [0.3]
 [0.6]
 [2.7]
 [3. ]]


In [44]:
V8 = V3 + V4
print(V8)

[[ 5.2]
 [ 1.3]
 [ 2.6]
 [11.7]
 [13. ]]


In [45]:
V9 = V3 + (0.5*V4)
print(V9)

[[ 4.6 ]
 [ 1.15]
 [ 2.3 ]
 [10.35]
 [11.5 ]]


In [46]:
V10 = V3 - V4
print(V10)

[[2.8]
 [0.7]
 [1.4]
 [6.3]
 [7. ]]


In [47]:
print(V3 - V3)

[[0]
 [0]
 [0]
 [0]
 [0]]


In [48]:
print(M)

[[ 1  2  4  5]
 [ 0 -1 -2 10]]


In [49]:
print(M2)

[[-1 -2 -3]
 [-4 -5 -6]]


In [50]:
print (M3)

[[ 0  1 10]
 [20  0 30]]


In [51]:
M7= M2 + M3
print(M7)

[[-1 -1  7]
 [16 -5 24]]


In [52]:
M8 = 2*M2 + M3
print(M8)

[[ -2  -3   4]
 [ 12 -10  18]]


In [53]:
M8 = M2 - M2
print(M8)

[[0 0 0]
 [0 0 0]]


In [54]:
M8 = M3 - M2
print(M8)

[[ 1  3 13]
 [24  5 36]]
